### ISSUE TITLE
Use Go modules

### ISSUE THREAD

**Issue by mvdan** [deroproject/graviton#3]
This repository seems to use a vendor directory instead of modules, kind of how most people developed Go code 3-4 years ago. Is there a particular reason for that?

I'm happy to help you transition or answer questions. The official docs are at https://golang.org/ref/mod.

**Comment by CaptainDero** [comment]
> This repository seems to use a vendor directory instead of modules, kind of how most people developed Go code 3-4 years ago. Is there a particular reason for that?  

May be old habits :) . 
But there are plans to shift to modules.

> I'm happy to help you transition or answer questions. The official docs are at https://golang.org/ref/mod.

Thanks for your offer. 
Please share some good approach that no internet connection or any access is required to any repo during building. It should be able to compile on offline machine just by git clone or source download without any extra pings.

**Comment by mvdan** [comment]
Well, in "module mode" a command like `go build` will only download dependencies which are not in the cache. If you run `go mod download` whenever go.mod changes or after a git clone/pull in the module, then a `go build` or `go test` should never download anything else.

You can still use `go mod vendor` to have something similar to the old-style vendoring. I'd discourage that in general, though, just because it's going to make the git repository unnecessarily large and doesn't really win you much. Builds with modules are already reproducible by default, without the need for vendor dirs :)

**Comment by CaptainDero** [comment]
`go mod vendor`  looks reasonable as it does not do extra pings and thus prevents some analytics on DERO users.

**Comment by mvdan** [comment]
The vendor directory will only be used for people who build graviton directly, though. Anyone using graviton as a dependency will skip the vendor directory entirely, so they'd have to do their own vendoring or use their own proxy if they did not want to hit github.com or proxy.golang.org. So I'm not entirely sure the vendor directory here really wins you anything at all.
