### ISSUE TITLE
slice bounds out of range panic in Unmarshal

### ISSUE THREAD

**Issue by mvdan** [deroproject/graviton#4]
```
panic: runtime error: slice bounds out of range [931:918]

goroutine 4042265 [running]:
github.com/deroproject/graviton.(*Proof).Unmarshal(0xc0195b4fd8, 0xc016f8b000, 0x396, 0x800, 0xc00dca5b80, 0x7fcabd71e838)
        /go/pkg/mod/github.com/deroproject/graviton@v0.0.0-20200906044921-89e9e09f9601/proof.go:192 +0x785
gitlab.com/vocdoni/go-dvote/statedb/gravitonstate.Verify(0xc014e72380, 0x20, 0x20, 0xc016f8b000, 0x396, 0x800, 0xc00dca5b80, 0x20, 0x40, 0xc0195b50c8, ...)
        /src/statedb/gravitonstate/graviton.go:392 +0x95
```

I don't have a reproducer program at hand right now, nor an input to Unmarshal to cause the panic, but I think the edge case is fairly easy to reason about.

Since the input bytes determine `tracelength` and `tracebits`, we could make those be long, and then abruptly end the input shortly after, causing `copy(p.trace[i], buf[done:])` to panic.

I think there should be bounds checks before each `buf[done:]` slice expression, as otherwise you risk panics. Those inputs should error instead, given that the function already returns an error.

I could provide a patch, but I thought an issue would be better since this fix might need careful thought - particularly with the tests.

**Comment by mvdan** [comment]
Friendly ping @CaptainDero. Would you review a patch?

**Comment by CaptainDero** [comment]
@mvdan , Sorry missed it, will look into.

**Comment by CaptainDero** [comment]
Patch [mentioned on]( https://github.com/mvdan/go-dvote/commit/fbfa15a097c7799514b27edf790bb911e9a8801c ) is good to go.

**Comment by mvdan** [comment]
Sorry, I don't understand. That patch downstream is not a fix, it's just a workaround.

**Comment by CaptainDero** [comment]
I know that, use it for time being in your project. As there are some other developments too going in Graviton and main repo will be updated with them.
